# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_sayhello'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayhello',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
