# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-02 04:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_sayhello_message'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='classification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
