# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160602_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
