# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-02 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160602_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 17, 48, 36, 101511, tzinfo=utc)),
        ),
    ]
